# -*- coding: utf-8 -*-
LANGS = {
    'ru': {
        'open_file': '📁 Открыть портрет SF1',
        'open_portrait': '📁 Открыть портрет',
        'open_png_file': '📁 Открыть PNG',
        'save_png': '💾 Сохранить PNG',
        'save_log': '📝 Сохранить лог',
        'palette': '💾 Палитра',
        'save_bin': '💾 Сохранить BIN',
        'open_png': '📁 Открыть PNG',
        'scale_up': '🔍 Увеличить',
        'scale_down': '🔎 Уменьшить',
        'language': 'Язык:',
        'edit_animations': '✏️ Редактировать анимацию'
    },
    'en': {
        'open_file': '📁 Open SF1 Portrait',
        'open_portrait': '📁 Open Portrait',
        'open_png_file': '📁 Open PNG',
        'save_png': '💾 Save PNG',
        'save_log': '📝 Save Log',
        'palette': '💾 Palette',
        'save_bin': '💾 Save BIN',
        'open_png': '📁 Open PNG',
        'scale_up': '🔍 Zoom In',
        'scale_down': '🔎 Zoom Out',
        'language': 'Language:',
        'edit_animations': '✏️ Edit Animations'
    },
    'it': {
        'open_file': '📁 Apri ritratto SF1',
        'open_portrait': '📁 Apri ritratto',
        'open_png_file': '📁 Apri PNG',
        'save_png': '💾 Salva PNG',
        'save_log': '📝 Salva Log',
        'palette': '💾 Palette',
        'save_bin': '💾 Salva BIN',
        'open_png': '📁 Apri PNG',
        'scale_up': '🔍 Ingrandisci',
        'scale_down': '🔎 Riduci',
        'language': 'Lingua:',
        'edit_animations': '✏️ Modifica Animazioni'
    },
    'fr': {
        'open_file': '📁 Ouvrir portrait SF1',
        'open_portrait': '📁 Ouvrir portrait',
        'open_png_file': '📁 Ouvrir PNG',
        'save_png': '💾 Enregistrer PNG',
        'save_log': '📝 Enregistrer log',
        'palette': '💾 Palette',
        'save_bin': '💾 Enregistrer BIN',
        'open_png': '📁 Ouvrir PNG',
        'scale_up': '🔍 Zoom avant',
        'scale_down': '🔎 Zoom arrière',
        'language': 'Langue:',
        'edit_animations': '✏️ Modifier Animations'
    },
    'es': {
        'open_file': '📁 Abrir retrato SF1',
        'open_portrait': '📁 Abrir retrato',
        'open_png_file': '📁 Abrir PNG',
        'save_png': '💾 Guardar PNG',
        'save_log': '📝 Guardar Log',
        'palette': '💾 Palette',
        'save_bin': '💾 Guardar BIN',
        'open_png': '📁 Abrir PNG',
        'scale_up': '🔍 Ampliar',
        'scale_down': '🔎 Reducir',
        'language': 'Idioma:',
        'edit_animations': '✏️ Editar Animaciones'
    },
    'ja': {
        'open_file': '📁 ポートレートを開く',
        'open_portrait': '📁 ポートレートを開く',
        'open_png_file': '📁 PNGを開く',
        'save_png': '💾 PNGを保存',
        'save_log': '📝 ログを保存',
        'palette': '💾 パレット',
        'save_bin': '💾 BINを保存',
        'open_png': '📁 PNGを開く',
        'scale_up': '🔍 拡大',
        'scale_down': '🔎 縮小',
        'language': '言語:',
        'edit_animations': '✏️ アニメーションを編集'
    },
    'pt': {
        'open_file': '📁 Abrir retrato SF1',
        'open_portrait': '📁 Abrir retrato',
        'open_png_file': '📁 Abrir PNG',
        'save_png': '💾 Salvar PNG',
        'save_log': '📝 Salvar log',
        'palette': '💾 Palette',
        'save_bin': '💾 Salvar BIN',
        'open_png': '📁 Abrir PNG',
        'scale_up': '🔍 Aumentar zoom',
        'scale_down': '🔎 Diminuir zoom',
        'language': 'Idioma:',
        'edit_animations': '✏️ Editar Animações'
    },
    'el': {
        'open_file': '📁 Άνοιγμα πορτρέτου SF1',
        'open_portrait': '📁 Άνοιγμα πορτρέτου',
        'open_png_file': '📁 Άνοιγμα PNG',
        'save_png': '💾 Αποθήκευση PNG',
        'save_log': '📝 Αποθήκευση αρχείου καταγραφής',
        'palette': '💾 Palette',
        'save_bin': '💾 Αποθήκευση BIN',
        'open_png': '📁 Άνοιγμα PNG',
        'scale_up': '🔍 Μεγέθυνση',
        'scale_down': '🔎 Σμίκρυνση',
        'language': 'Γλώσσα:',
        'edit_animations': '✏️ Επεξεργασία Κινήσεων'
    },
}